import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:csv/csv.dart';
import 'dart:convert';
import '../models/book.dart';
import '../services/supabase_service.dart';

class CsvUploadScreen extends StatefulWidget {
  const CsvUploadScreen({super.key});

  @override
  State<CsvUploadScreen> createState() => _CsvUploadScreenState();
}

class _CsvUploadScreenState extends State<CsvUploadScreen> {
  final SupabaseService _supabaseService = SupabaseService();
  bool _isUploading = false;
  String? _statusMessage;
  int _totalBooks = 0;
  int _uploadedBooks = 0;

  Future<void> _pickAndUploadCsv() async {
    try {
      // Pick CSV file
      FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['csv'],
        withData: true,
      );

      if (result == null || result.files.first.bytes == null) {
        setState(() {
          _statusMessage = 'No file selected';
        });
        return;
      }

      setState(() {
        _isUploading = true;
        _statusMessage = 'Reading CSV file...';
        _uploadedBooks = 0;
      });

      // Read and parse CSV
      final bytes = result.files.first.bytes!;
      final csvString = utf8.decode(bytes);
      final List<List<dynamic>> csvData = const CsvToListConverter().convert(
        csvString,
        eol: '\n',
      );

      if (csvData.isEmpty) {
        setState(() {
          _statusMessage = 'CSV file is empty';
          _isUploading = false;
        });
        return;
      }

      // Skip header row and validate
      final dataRows = csvData.skip(1).toList();
      _totalBooks = dataRows.length;

      if (_totalBooks == 0) {
        setState(() {
          _statusMessage = 'No data rows found in CSV';
          _isUploading = false;
        });
        return;
      }

      setState(() {
        _statusMessage = 'Uploading $_totalBooks books...';
      });

      // Upload books one by one
      for (int i = 0; i < dataRows.length; i++) {
        final row = dataRows[i];

        if (row.length < 6) {
          setState(() {
            _statusMessage = 'Row ${i + 2} has insufficient columns. Skipping...';
          });
          continue;
        }

        try {
          final book = Book(
            id: '', // Will be auto-generated by Supabase
            title: row[0].toString().trim(),
            author: row[1].toString().trim(),
            rack: row[2].toString().trim(),
            shelf: row[3].toString().trim(),
            row: row[4].toString().trim(),
            position: row[5].toString().trim(),
          );

          await _supabaseService.addBook(book);
          
          setState(() {
            _uploadedBooks++;
            _statusMessage = 'Uploaded $_uploadedBooks of $_totalBooks books...';
          });
        } catch (e) {
          setState(() {
            _statusMessage = 'Error on row ${i + 2}: $e. Continuing...';
          });
          await Future.delayed(const Duration(milliseconds: 500));
        }
      }

      setState(() {
        _statusMessage = 'Success! Uploaded $_uploadedBooks of $_totalBooks books.';
        _isUploading = false;
      });

      // Show success message
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Successfully uploaded $_uploadedBooks books!'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      setState(() {
        _statusMessage = 'Error: $e';
        _isUploading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('CSV Upload'),
      ),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 600),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const Icon(
                  Icons.upload_file,
                  size: 80,
                  color: Colors.blue,
                ),
                const SizedBox(height: 24),
                const Text(
                  'Bulk Upload Books',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 16),
                const Text(
                  'Upload a CSV file with the following columns:',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 16),
                ),
                const SizedBox(height: 12),
                Card(
                  color: Colors.grey[100],
                  child: const Padding(
                    padding: EdgeInsets.all(16.0),
                    child: Text(
                      'title,author,rack,shelf,row,position',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontFamily: 'monospace',
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                const Text(
                  'Example CSV:',
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 8),
                Card(
                  color: Colors.grey[100],
                  child: const Padding(
                    padding: EdgeInsets.all(16.0),
                    child: Text(
                      'title,author,rack,shelf,row,position\n'
                      'The Great Gatsby,F. Scott Fitzgerald,A,2,3,5\n'
                      '1984,George Orwell,B,1,4,7',
                      style: TextStyle(
                        fontFamily: 'monospace',
                        fontSize: 12,
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 32),
                if (_statusMessage != null) ...[
                  Card(
                    color: _isUploading ? Colors.blue[50] : Colors.green[50],
                    child: Padding(
                      padding: const EdgeInsets.all(16.0),
                      child: Column(
                        children: [
                          if (_isUploading && _totalBooks > 0)
                            LinearProgressIndicator(
                              value: _uploadedBooks / _totalBooks,
                            ),
                          if (_isUploading && _totalBooks > 0)
                            const SizedBox(height: 12),
                          Text(
                            _statusMessage!,
                            textAlign: TextAlign.center,
                            style: const TextStyle(fontSize: 14),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),
                ],
                ElevatedButton.icon(
                  onPressed: _isUploading ? null : _pickAndUploadCsv,
                  icon: _isUploading
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Icon(Icons.file_upload),
                  label: Text(
                    _isUploading ? 'Uploading...' : 'Select CSV File',
                    style: const TextStyle(fontSize: 16),
                  ),
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
